### ISSUE TITLE
打算支持1.12.2吗

### ISSUE THREAD

**Issue by 3269199948** [RecursiveG/UniSkinMod#10]
如题，

**Comment by xfl03** [comment]
基本上就是改个Forge版本号的事情，皮肤这一块到1.12.2没什么大变化，您可以考虑自己移植一下

**Comment by xfl03** [comment]
https://github.com/xfl03/UniSkinMod
~~请给五星好评~~

**Comment by RecursiveG** [comment]
本模组目前没有继续开发计划，如果有需要请转用[CSL](http://www.mcbbs.net/thread-269807-1-1.html).
