### ISSUE TITLE
[1.8]请升级Readme.md

### ISSUE THREAD

**Issue by wfjsw** [RecursiveG/UniSkinMod#2]
UniSkinAPI已支持，但在说明文件中未提及配置方式
请更新说明文件

**Comment by RecursiveG** [comment]
New version of UniSkinMod for MC1.8 has been merged to master.
Old style link support removed. Documents for UniSkinAPI config added.
See commit a7d534ea08ca669c3d0053fb2e1e0b8a917c91d9
