### ISSUE TITLE
1.7.10-forge-10.10.0.1206 无法正常工作

### ISSUE THREAD

**Issue by kice** [RecursiveG/UniSkinMod#3]
SkinCore 里面的injectTexture没有调用。麻烦检查下代码。错误日志里面全部都是info，没有看见error。
1.7.10-forge-10.10.0.1206

目前我是知道CoreTransformer里面的injectCode有被调用，奈何我不会java，所以没有具体分析下去。

**Comment by RecursiveG** [comment]
1.7.10分支不再维护
