### ISSUE TITLE
关于自己的皮肤的模型识别

### ISSUE THREAD

**Issue by esterTion** [RecursiveG/UniSkinMod#5]
从1.8开始的，因为非正版服务器什么皮肤都不显示了，之前还用skinme替代，现在skinme改的奇奇怪怪的，没什么好感
自己的皮肤显示十分鬼畜，缺胳膊、背部消失
看其他玩家是好的，其他玩家看自己也是好的，只有自己这里是奇怪的

**Comment by RecursiveG** [comment]
MC版本，Forge版本 以及mod版本?

**Comment by esterTion** [comment]
1.9+1833
1.9-pre1和1.9-pre2-dev都有同样的问题，1.8的时候其实也有这个问题，当时换的skinme源
[未启用uniskin](http://i2.hdslb.com/bfs/archive/79074f57bed87fe40db8859f067c6539a50d5b04.png)
[启用uniskin，且配置文件各项留空](http://i2.hdslb.com/bfs/archive/b3e8afe8ce8eef67920e2a220a8dd0eb43fd0be7.png)
minecraft_username:lcz970

**Comment by RecursiveG** [comment]
请尝试这个版本
[https://github.com/RecursiveG/UniSkinMod/releases/tag/1.4-dev2](https://github.com/RecursiveG/UniSkinMod/releases/tag/1.4-dev2)
另外 1.9 forge尚不稳定，若不同 forge 版本之间不能通用请见谅。

**Comment by esterTion** [comment]
更新后确实好了。迷之透明皮肤，我整的不是透明啊

**Comment by RecursiveG** [comment]
可能是因为你的皮肤的背景是不透明的，然后就不知道怎么回事挂掉了。。。

**Comment by esterTion** [comment]
_(:3」∠)_我拿画图画的
