### ISSUE TITLE
Attempted to load class org/devinprogress/uniskinmod/UniSkinMod for invalid side SERVER

### ISSUE THREAD

**Issue by JonnyBrando** [RecursiveG/UniSkinMod#9]
Unable to use UniSkinMod 1.9.4 & 1.10 on a Private Server.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
>   IC2core (industrialcraft-2-2.6.26-ex110.jar)
>   CreativePatchingLoader (CreativeCore v1.5.1 mc1.10.2.jar)
>   FMLPlugin (InventoryTweaks-1.61-58.jar)
>   MMFMLCorePlugin (MultiMine-1.10.jar)
>   MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
>   PlayerAPIPlugin (PlayerAPI-1.10.2-1.0.jar)
>   SCFMLCorePlugin (StalkerCreepers-1.10.jar)
>   ItemPatchingLoader (ItemPhysic Full 1.3.2 mc1.10.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // I'm sorry, Dave.
> 
> Time: 9/12/16 3:51 PM
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: org.devinprogress.uniskinmod.UniSkinMod
>   at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
>   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
>   at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
>   at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: org.devinprogress.uniskinmod.UniSkinMod
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
>   at java.lang.Class.forName0(Native Method)
>   at java.lang.Class.forName(Class.java:348)
>   at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:503)
>   at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
>   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
>   at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
>   ... 5 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3016fd5e from coremod FMLCorePlugin
>   at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
>   at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
>   ... 32 more
> Caused by: java.lang.RuntimeException: Attempted to load class org/devinprogress/uniskinmod/UniSkinMod for invalid side SERVER
>   at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56)
>   at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
>   ... 34 more
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.10.2
>   Operating System: Windows 8.1 (amd64) version 6.3
>   Java Version: 1.8.0_74, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 302951376 bytes (288 MB) / 527667200 bytes (503 MB) up to 8563130368 bytes (8166 MB)
>   JVM Flags: 7 total; -Xms350m -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:+AggressiveOpts -Xmn256M
>   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>   FML: MCP 9.32 Powered by Forge 12.18.1.2045 47 mods loaded, 47 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
>   UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2045-universal.jar) 
>   UC  Forge{12.18.1.2045} [Minecraft Forge](forge-1.10.2-12.18.1.2045-universal.jar) 
>   UC  creativecoredummy{1.0.0} [CreativeCoreDummy](minecraft.jar) 
>   UC  itemphysic{1.3.0} [ItemPhysic](minecraft.jar) 
>   UC  PlayerAPI{1.0} [Player API](minecraft.jar) 
>   UC  cfm{4.0.1} [MrCrayfish's Furniture Mod]([1.10]cfm-universal-4.0.1.jar) 
>   UC  movillages{1.5.2} [Mo' Villages]([1.9.4]Mo' Villages-1.5.2.jar) 
>   UC  bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.0c.jar) 
>   UC  BetterAchievements{0.3.0.30} [Better Achievements](BetterAchievements-1.10.2-0.3.0.30.jar) 
>   UC  betteragriculture{0.16} [Better Agriculture](BetterAgriculture_%28MC-1.10%29-0.16.jar) 
>   UC  BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
>   UC  BiomesOPlenty{4.1.0.2052} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2052-universal.jar) 
>   UC  chiselsandbits{11.7} [Chisels & Bits](chiselsandbits-11.7.jar) 
>   UC  IC2{2.6.26-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.26-ex110.jar) 
>   UC  JEI{3.7.9.236} [Just Enough Items](jei_1.10.2-3.7.9.236.jar) 
>   UC  forestry{5.2.5.217} [Forestry](forestry_1.10.2-5.2.5.217.jar) 
>   UC  gravestone{1.5.4} [Gravestone](GraveStone Mod 1.5.4.jar) 
>   UC  LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
>   UC  InGameInfoXML{2.8.1.85} [InGame Info XML](InGameInfoXML-1.10.2-2.8.1.85-universal.jar) 
>   UC  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
>   UC  InventoryPets{1.4.8.1} [Inventory Pets](inventorypets-1.10-1.4.8.1.jar) 
>   UC  inventorysorter{0.10.0+42} [Simple Inventory sorting](inventorysorter-1.10-0.10.0+42.jar) 
>   UC  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
>   UC  journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
>   UC  lucky{7.3.0} [Lucky Block](LuckyBlock_1-10-2_v7-3-0.jar) 
>   UC  malisiscore{1.9.4-4.0.2} [MalisisCore](malisiscore-1.9.4-4.0.2.jar) 
>   UC  malisisblocks{1.9.4-4.0.1} [Malisis Blocks](malisisblocks-1.9.4-4.0.1.jar) 
>   UC  malisisdoors{1.9.4-5.0.1} [MalisisDoors](malisisdoors-1.9.4-5.0.1.jar) 
>   UC  RadixCore{1.10.2-2.1.2} [RadixCore](RadixCore-1.10.2-2.1.2-universal.jar) 
>   UC  MCA{1.10.2-5.2.1} [Minecraft Comes Alive](MCA-1.10.2-5.2.1-universal.jar) 
>   UC  AS_MultiMine{1.5.4} [Multi Mine](MultiMine-1.10.jar) 
>   UC  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2a.jar) 
>   UC  parachutemod{1.5.2} [Parachute Mod](parachutemod-ng-1.10.2-1.5.2-409.jar) 
>   UC  progressiveautomation{1.6.48} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.48.jar) 
>   UC  Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
>   UC  AS_Ruins{16.2} [Ruins Spawning System](Ruins-1.10.jar) 
>   UC  SophisticatedWolves{3.6.1} [SophisticatedWolves](SophisticatedWolves-3.6.2.jar) 
>   UC  Chameleon{1.9.4-2.1.6} [Chameleon](Chameleon-1.9.4-2.1.6.jar) 
>   UC  StorageDrawers{1.9.4-3.2.1} [Storage Drawers](StorageDrawers-1.9.4-3.2.1.jar) 
>   UC  mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
>   UC  tconstruct{1.10.2-2.4.0.jenkins312} [Tinkers' Construct](TConstruct-1.10.2-2.4.0.jenkins312.jar) 
>   UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
>   UC  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
>   UC  bspkrsCore{7.2} [bspkrsCore]([1.10]bspkrsCore-universal-7.2.jar) 
>   UE  uniskinmod{1.5-dev1} [Universal Skin Mod]([1.9.4-1.10.2]UniSkinMod-universal-1.5-dev1.jar) 
>   UC  creativecore{1.5.0} [CreativeCore](CreativeCore v1.5.1 mc1.10.2.jar) 
>   Loaded coremods (and transformers): 
> BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
>   mods.betterfoliage.loader.BetterFoliageTransformer
> IC2core (industrialcraft-2-2.6.26-ex110.jar)
> 
> CreativePatchingLoader (CreativeCore v1.5.1 mc1.10.2.jar)
> 
> FMLPlugin (InventoryTweaks-1.61-58.jar)
>   invtweaks.forge.asm.ContainerTransformer
> MMFMLCorePlugin (MultiMine-1.10.jar)
>   atomicstryker.multimine.common.fmlmagic.MMTransformer
> MalisisCorePlugin (malisiscore-1.9.4-4.0.2.jar)
>   net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
>   net.malisis.core.util.chunkblock.ChunkBlockTransformer
>   net.malisis.core.renderer.transformer.MalisisRendererTransformer
>   net.malisis.core.renderer.icon.asm.TextureMapTransformer
>   net.malisis.core.util.clientnotif.ClientNotifTransformer
> PlayerAPIPlugin (PlayerAPI-1.10.2-1.0.jar)
>   api.player.forge.PlayerAPITransformer
> SCFMLCorePlugin (StalkerCreepers-1.10.jar)
>   atomicstryker.stalkercreepers.common.SCTransformer
> ItemPatchingLoader (ItemPhysic Full 1.3.2 mc1.10.2.jar)
>   com.creativemd.itemphysic.ItemTransformer
>   Pulsar/tconstruct loaded Pulses: 
>       - TinkerCommons (Enabled/Forced)
>       - TinkerWorld (Enabled/Not Forced)
>       - TinkerTools (Enabled/Not Forced)
>       - TinkerSmeltery (Enabled/Not Forced)
>       - TinkerGadgets (Enabled/Not Forced)
>       - TinkerOredict (Enabled/Forced)
>       - TinkerIntegration (Enabled/Forced)
>       - TinkerFluids (Enabled/Forced)
>       - TinkerMaterials (Enabled/Forced)
>       - chiselsandbitsIntegration (Enabled/Not Forced)
>       - WailaIntegration (Enabled/Not Forced)
> 
>   Profiler Position: N/A (disabled)
>   Is Modded: Definitely; Server brand changed to 'fml,forge'
>   Type: Dedicated Server (map_server.txt)

**Comment by RecursiveG** [comment]
You do not need to install this mod in server. Just on the client side.

**Comment by JonnyBrando** [comment]
Would installing it on a server not show other players the skin of your choosing?

Just trying to make it so that when I play with my kids in my 'offline mode private server', each person sees the skins that everyone else has chosen for themselves.

It has worked this way in the past.

**Comment by RecursiveG** [comment]
Em... This problem has been reported for several times in fact.
But I do not have enough time to deal with it.
Generally speaking, I haven't decided when to update this MOD.
Sorry about that.
